# Generated by Django 3.2.17 on 2023-02-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '監視サイト', 'verbose_name_plural': 'サイト一覧'},
        ),
    ]
