# Generated by Django 3.2.17 on 2023-02-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
    ]
