# Generated by Django 3.2.17 on 2023-02-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='puvlisheded_at',
            new_name='publisheded_at',
        ),
    ]
