# Generated by Django 3.2.17 on 2023-02-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_record_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table=None,
        ),
    ]
