# Generated by Django 3.2.17 on 2023-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_rename_publisheded_at_record_publisheded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='publisheded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
