# Generated by Django 3.2.17 on 2023-02-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_record_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '開発記録', 'verbose_name_plural': '記録一覧'},
        ),
    ]
