# Generated by Django 3.2.17 on 2023-02-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_record_publisheded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
    ]
