# Generated by Django 3.2.17 on 2023-02-07 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_remove_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
