# Generated by Django 3.2.17 on 2023-02-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20230207_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
