# Generated by Django 3.2.17 on 2023-02-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_rename_created_at_record_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='publisheded_date',
            new_name='published_date',
        ),
    ]
