# Generated by Django 3.2.17 on 2023-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_rename_publisheded_date_record_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(verbose_name='記事'),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
