# Generated by Django 3.2.17 on 2023-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20230207_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200, verbose_name='標題'),
        ),
    ]
